### ISSUE TITLE
Codegen/compiler bug with matching nested unions

### ISSUE THREAD

**Issue by kirbyfan64** [felix-lang/felix#78] opened 2016-03-24 17:05 UTC
This code:

```
union BuiltinType =
    | TBint
;

union Type =
    | Tany
    | Tbuiltin of BuiltinType
;

instance Str[Type] {
    fun str(ty: Type) => match ty with
        | #Tany => 'Tany'
        | Tbuiltin tb => tb._strr
    endmatch;
}

println Tany.str;
```

Results in invalid codegen:

```
Warning VR_self rep not handled right?
/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp: In function ‘void flxusr::vd::_init_()’:
/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp:34:8: error: variable or field ‘tb’ declared void
   void tb;
        ^
compilation terminated due to -Wfatal-errors.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++11" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-O1" "-I/media/ryan/stuff/felix/build/release/share/lib/rtl" "-I/media/ryan/stuff/felix/build/release/host/lib/rtl" "/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp" -o "/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd_dynamic.o" FAILED
Error 1 in flx: [strerror_r] Failed to find text for error number 1
```

If I change the last line to `println (Tbuiltin TBint).str`, then I get:

```
Fatal error: exception File "build/release/src/compiler/flx_cpp_backend/flx_vgen.ml", line 138, characters 15-21: Assertion failed
Felix compilation "/media/ryan/stuff/felix/build/release/host/bin/flxg" "-q" "--inline=25" "--output_dir=/media/ryan/stuff/.felix/cache" "--cache_dir=/media/ryan/stuff/.felix/cache" "-I/media/ryan/stuff/felix/build/release/share/lib" "-I/media/ryan/stuff/felix/build/release/host/lib" "--syntax=@/media/ryan/stuff/felix/build/release/share/lib/grammar/grammar.files" "--automaton=/media/ryan/stuff/.felix/cache/media/ryan/stuff/felix/build/release/share/lib/grammar/grammar.files/syntax.automaton" "--import=plat/flx.flxh" "std" "/home/ryan/flx_tst/val/vd.flx" failed
Error 1 in flx: [strerror_r] Failed to find text for error number 1
```

**Comment by kirbyfan64** [comment] 2016-03-24 21:30
This is a bug in nested unions. Here's another repro:

```
union BuiltinType =
    | TBint
;

union Type =
    | Tany
    | Tbuiltin of BuiltinType
;

fun tymatch(ta: Type) => match ta with
    | Tbuiltin tba => caseno tba
endmatch;

println$ tymatch Tany;
```

That outputs:

```
Warning VR_self rep not handled right?
/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp: In function ‘void flxusr::vd::_init_()’:
/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp:34:8: error: variable or field ‘tba’ declared void
   void tba;
        ^
compilation terminated due to -Wfatal-errors.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++11" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-O1" "-I/media/ryan/stuff/felix/build/release/share/lib/rtl" "-I/media/ryan/stuff/felix/build/release/host/lib/rtl" "/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp" -o "/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd_dynamic.o" FAILED
Error 1 in flx: [strerror_r] Failed to find text for error number 1
```

And changing the last line to `println$ tymatch$ Tbuiltin TBint;` results in:

```
Fatal error: exception File "build/release/src/compiler/flx_cpp_backend/flx_vgen.ml", line 138, characters 15-21: Assertion failed
Felix compilation "/media/ryan/stuff/felix/build/release/host/bin/flxg" "-q" "--inline=25" "--output_dir=/media/ryan/stuff/.felix/cache" "--cache_dir=/media/ryan/stuff/.felix/cache" "-I/media/ryan/stuff/felix/build/release/share/lib" "-I/media/ryan/stuff/felix/build/release/host/lib" "--syntax=@/media/ryan/stuff/felix/build/release/share/lib/grammar/grammar.files" "--automaton=/media/ryan/stuff/.felix/cache/media/ryan/stuff/felix/build/release/share/lib/grammar/grammar.files/syntax.automaton" "--import=plat/flx.flxh" "std" "/home/ryan/flx_tst/val/vd.flx" failed
Error 1 in flx: [strerror_r] Failed to find text for error number 1
```

**Comment by kirbyfan64** [comment] 2016-03-24 21:40
Also, note that, in any of the examples, removing the `Tbuiltin` branches will remove any issues.

**Comment by skaller** [comment] 2016-03-24 22:49
> On 25 Mar 2016, at 08:30, Ryan Gonzalez <notifications@github.com> wrote:
> 
> This is a bug in nested unions. Here's another repro:
> 
> union BuiltinType =
>     | TBint
> ;
> 
> union Type =
>     | Tany
>     | Tbuiltin of BuiltinType
> ;
> 
> fun tymatch(ta: Type) => match ta with
>     | Tbuiltin tba => caseno tba
> endmatch;
> 
> println$ tymatch Tany;
> 
> That outputs:
> 
> Warning VR_self rep not handled right?
> /media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp: In function ‘void flxusr::vd::_init_()’:
> /media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/vd.cpp:34:8: error: variable or field ‘tba’ declared void
>    void tba;
>         ^

Roughly what’s happening is this: When you do

	union X = A of atype;

there is a special optimisation, A a is replaced by a. The Ocaml name of the
representation is VR_self: the (sole) constructor application to its argument is
replaced by the argument.

The problem here seems to be that there is no argument :)
Either the argument is taken as unit or void, not sure.

Coneptually the code gen is supposed to represent unit by void,
and &unit by NULL, this means units have to be elided. However
eliding them is very hard. 

There are other cases where unit fails, for example, try read/write 
on schannel[unit].

So in your modified example the problem is trapped in the compiler:

  match cal_variant_rep bsym_table ut with
  | VR_self -> assert false (* will fail if there's one trivial case! FIX! Felix should elide completely *)
  | VR_int -> ce_atom ("/*VR_int*/"^(si v))
  | VR_nullptr -> ce_cast "void* /*VR_nullptr*/ " (ce_atom (si v))
  | VR_packed -> ce_cast "void* /*VR_packed*/ " (ce_atom (si v))
  | VR_uctor -> ce_atom ("::flx::rtl::_uctor_(" ^ si v ^ ",0)") 

The compiler is saying that VR_self representation shouldn’t exist in
the code generator, it should have been reduced to the argument of
the sole constructor .. which it was in the quoted example, in which
case it generated type “void” for the argument type.

So these are actually separate bugs. The second bug is a “nested union”
kind of bug, the VR_self representation eliminiator isn’t recursing.
The first bug is a failure to handle unit or void or “no argument”
for a VR_self type sole constructor which is eliminated.

As a temporary fix to your code you can provide BuiltinType
with two cases which changes the representation to VR_int.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment] 2016-03-26 15:17
I now have all Ryan’s bug cases working. Some regression tests broke and
are being fixed.

There is a small problem though.

	BEXPR_case_index (i,uv),int_t

is an expression which finds the case index of a value ut of a union (or sum) type.
It’s just an int. In the lookup module, I calculate int_t by literally doing a lookup
for the type name “int”. It had better be in the library!

However in the code the eliminates unions with one constructor,
I have to remove the above expression since the union type is about
to be deleted entirely. The case index is clearly just 0 of type int_t.

The problem is, I can’t do a lookup to find int_t at this point, we’re past
binding unbound types to bound types. So I added a BTYP_int to
the compiler (and a BEXPR_int j as well). And I use that.

The problem is the type of such a value does NOT agree with the type
of the index of an ordinary union. They’re both going to end up as
a C++ int but in the meantime the user is entitled to write stuff like:

	caseno x = caseno y

and x might be of type BTYP_int and y of type BTYP_inst (an abstract type
looked up in the library with name “int”). This is going to fail.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment] 2016-03-27 11:28
This should be fixed now

**Closed by skaller** 2016-03-27 11:28 UTC
