### ISSUE TITLE
Codegen (or maybe precedence?) bug

### ISSUE THREAD

**Issue by kirbyfan64** [felix-lang/felix#77] opened 2015-12-29 23:35 UTC
I figured I should probably start using the issue tracker a bit more! ;)

This:

```
fun something: int * int -> bool = '$1+$2';

f := 0;
if not something$ f, 0 perform halt '123';
```

Results in:

```
/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/ax.cpp:43:65: fatal error: 
      member reference type 'bool' is not a pointer
      if(!(!(FLX_NEWP(_a65908_something)(FLX_FPAR_PASS_ONLY)))->clone()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
C++ compilation /media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/ax.cpp failed
[flx] C++ compilation /media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/ax.cpp failed
```

Doing one of the following makes the problem disappear:
- Replacing the `$` in the call to `something`with parens.
- Removing the `not` in the if statement.
- Parenthesizing the entire call:

```
if not (something$ f, 0) perform halt '123';
```

Here's a slightly different but related case:

```
fun something: int * int -> bool = '$1+$2';
fun something(f: int)(p: int) => something (f, p);

f := 0;
if not f.something$ 0 perform halt '123';
```

which results in:

```
/media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/ax.cpp:37:26: fatal error: 
      member reference type 'bool' is not a pointer
      if(!(!_mkp_65921)->clone()
          ~~~~~~~~~~~~~  ^
1 error generated.
C++ compilation /media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/ax.cpp failed
[flx] C++ compilation /media/ryan/stuff/.felix/cache/home/ryan/flx_tst/val/ax.cpp failed
```

**Comment by skaller** [comment] 2015-12-30 00:47
> On 30 Dec 2015, at 10:35, Ryan Gonzalez <notifications@github.com> wrote:
> 
> I figured I should probably start using the issue tracker a bit more! ;)

And add bugs to the set of regression tests :)

> 
> This:
> 
> fun something: int * int -> bool = '$1+$2';
> 
> f := 0;
> if not something$ f, 0 perform halt '123';
> 
> Results in:
> 
> /media/ryan/stuff/felix/cache/home/ryan/flx_tst/val/axcpp:43:65: fatal error: 
>       member reference type 'bool' is not a pointer
>       if(!(!(FLX_NEWP(_a65908_something)(FLX_FPAR_PASS_ONLY)))->clone()
>           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
> 1 error generated

I have this, please see src/packages/logic.fdoc line 164.

fun something: int * int -> bool = '$1+$2';
var f = not something;
var y = f (1,1);
println$ y;


and get this:

/Users/skaller/.felix/cache/text/Users/skaller/felix/xx.cpp:45:13: fatal error:
      assigning to 'flxusr::xx::_ft60877 *' from incompatible type 'bool'
      PTF f = !(FLX_NEWP(_a60815_something)(FLX_FPAR_PASS_ONLY)); //assi...
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The problem is clear here: the function something is being APPLIED and the
result not-ed. This is wrong. We should be applying THIS function:

   fun lnot (f:T->bool) =>
     fun (x:T) => not (f x)
   ;

to a wrapper closure over the primitive something.
Here is the wrapper declaration:

//FUNCTION <60815>: _a60815_something
struct _a60815_something: _ft60877 {
  FLX_FMEM_DECL

  _at60876 _a60816;
  _a60815_something(FLX_FPAR_DECL_ONLY);
  _a60815_something* clone();
   ::flx::rtl::cl_t apply(_at60876 const &);
};

and here is the definition:

//FUNCTION <60815>: _a60815_something: Apply method
 ::flx::rtl::cl_t _a60815_something::apply(_at60876 const &_arg ){
  _a60816 = _arg;
      return (_a60816.data)[0] + (_a60816.data)[1] ;
    FLX_DROPTHRU_FAILURE("/Users/skaller/felix/xx.flx",1,1,1,44); // HACK! 
}

Note again: the type is “cl_t” which a compact linear type.
Bool is a compact linear type. But cl_t is actually an integer type.
So the result is going to be very bad because something is incorrectly
defined. Felix does NOT allow integers to be treated as bools!

However this doesn’t explain the problem. The question is why is the
wrong “not” being used. And here is the answer:

GRAMMAR
  //$ Logical negation (not).
  x[snot_condition_pri] := "not" x[snot_condition_pri]  =># "`(ast_not ,_sr ,_2)";

DESUGAR
 | Lst [Id "ast_not"; sr; e] -> EXPR_not (xsr sr, ex e)

BIND
  | EXPR_not (sr,e) -> bexpr_not (be e)


(note there is no type checking!!!!)

So this explains the bug. The problem is I intrdocued “EXPR_not”
and “EXPR_andlist” and “EXPR_orlist” so the COMPILER could
do logic .. not for the end user!

Here is the binding of an EXPR_andlist:

  | EXPR_andlist (sri,ls) ->
    begin let mksum a b = Flx_strr.apl2 sri "land" [a;b] in
    match ls with
    | h::t -> be (List.fold_left mksum h t)
    | [] -> clierr sri "Not expecting empty and list"
    end

So you see this CORRECTLY binds to the user function “land”.

So the bug is clearly here:

  | EXPR_not (sr,e) -> bexpr_not (be e)

This should bind using the user function “lnot”.

The funny thing is half the reason for an explicit logical not combinator
was to get rid of expressions like

	!(!(!(!(!!x))))

which the code generator tends to make. The idea being the compiler
could reduce two nots into an identity.

Should be fixed now!

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Closed** 2017-08-29 13:38 UTC
Labels: bug, commentary
