### ISSUE TITLE
Still can't build it on Manjaro Linux!!!

### ISSUE THREAD

**Issue by Rencer** [felix-lang/felix#141] opened 2019-04-04 10:57 UTC
On Manjaro linux still impossible to build it..

Here is what I get after an HOUR of compiling:

> FLX_INSTALL_DIR=build/release build/release/host/bin/flx --felix=build.fpc \
	--usage=prototype --expect --input --nonstop \
	--indir=build/release/test/tutopt --regex='.*\.flx' build/release/test/tutopt
Processing 10 files
Processing [01/10]: mmap_01.flx
[FlxPkg:map_package_requirements] Error 1 executing flx_pkgconfig, args=list('--path+=build/release/host/config', '--path+=/usr/local/lib/felix/packages/host/config', '--field=cflags', '--keepleftmost', '@/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/mmap_01.resh')
BATCH MODE ERROR HANDLER
Processing [02/10]: sdlgui/gui_01_window_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.includes:6:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.includes:6:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01_dynamic.o" FAILED
Processing [03/10]: sdlgui/gui_02_font_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01_dynamic.o" FAILED
Processing [04/10]: sdlgui/gui_03_draw_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01_dynamic.o" FAILED
Processing [05/10]: sdlgui/gui_04_wm_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01_dynamic.o" FAILED
Processing [06/10]: sdlgui/gui_05_window_controller_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01_dynamic.o" FAILED
Processing [07/10]: sdlgui/gui_06_button_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01_dynamic.o" FAILED
Processing [08/10]: sdlgui/gui_07_editfield_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01_dynamic.o" FAILED
Processing [09/10]: sdlgui/gui_08_menu_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01_dynamic.o" FAILED
Processing [10/10]: sdlgui/gui_08_menu_02.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02_dynamic.o" FAILED
Batch result (00 OK + 10 FAIL)/10
Error 1 in flx: [strerror_r] Failed to find text for error number 1
make: [GNUmakefile:338: tutopt-check] Error 1 (ignored)
build/release/host/bin/flx --felix=build.fpc --usage=prototype --expect --nonstop --indir=build/release/test/extras --regex='.*\.flx' build/release/test
Processing 1 files
Processing [01/01]: gmp-01.flx
Opening syntax extensions /home/gofri/felix/src/packages/gmp.fdoc: line 199, cols 1 to 24
Parsed open of syntax extensions gmp_syntax
Batch result (01 OK + 00 FAIL)/ 1

**Comment by skaller** [comment] 2019-04-04 15:32
Felix has built just fine. The issue is with the configuration database assuming 
the wrong location for SDL. The build system does NOT test to find out where it is installed.
It *assumes* it is installed in /usr/local. On Debian based systems it will actually be in /usr not /usr/local if you installed it with apt-get. If you build it yourself, and used the default install location, it will be in /usr/local.

This issue exists because Felix itself does not build SDL and it does not try to detect where it is located either.

You can fix it by editing the database files build/release/host/config/sdl2*.fpc to contain the directory names relevant you your system. These changes will be clobbered if you rebuild it. To fix that you copy those files after editing them to $HOME/.felix/config, then a rebuild will copy those files on top of the defaults when you rebuild from scratch.

It's the responsibility of the user to ensure the location meta-data of third party libraries is correct.
The location varies from system to system. Even on Linux, as pointed out, it depends on where YOU put the files.

I cannot test any improvements, my main system is MacOSX. We build on Travis, which is Linux, but it is a remote CI server and so can't run SDL anyhow.

This line is the main problem:

```
cflags: -I/usr/local/include/SDL2
```

on YOUR system, it should probably read:

```
cflags: -I/usr/include/SDL2
```

This is issue is NOT a bug, it's a deficiency in the system: there is no program that looks for external libraries to see where they are located. You have to specify it manually, with a text editor.

You can try 

```
sdl2-config --cflags
```

to find out what the correct value is.

**Comment by loftsmen** [comment] 2019-04-06 08:10
@Rencer I've uploaded a [PKGBUILD](https://aur.archlinux.org/packages/felix/) into the AUR repository

This will build you a Felix package installable on Arch Linux, and distros based of it such as Manjaro.

Steps should be
```
sudo pacman -S ocmal python3 gcc gmp gsl sdl2 sdl2_ttf sdl2_gfx sdl2_image
git clone https://aur.archlinux.org/felix.git felix_aur
cd felix_aur
makepkg
pacman -U felix*.pkg.tar.xz
```

It has all the extras, and no warnings. Uploaded minutes ago, so please report any teething issues.

**Comment by loftsmen** [comment] 2019-04-06 08:14
If you don't want to install a package, fix up the SDL2 paths with this command.
```
sed -i 's|usr/local|usr|g' src/packages/sdl.fdoc
```

**Comment by skaller** [comment] 2019-04-06 10:17
However that change will be lost and/or cause a conflict next git pull.

The supported way to override system third party library meta-data is to put the *.fpc files required in $HOME/.felix/config. This works if you do a complete build from scratch. It may not work right for rebuilds etc yet. At present, fbuild copies these file over the top of the host/config files after copying the defaults in there.

**Comment by skaller** [comment] 2019-04-06 10:20
> I've uploaded a [PKGBUILD](https://aur.archlinux.org/packages/felix/) into the AUR repository

If you want to put a copy in felix make a directory in src/misc

**Comment by loftsmen** [comment] 2019-04-10 01:51
@skaller after https://github.com/felix-lang/felix/commit/1465571bea04075d7bb30974bfdf000180fbc6e1 this issue should be resolved.

**Comment by skaller** [comment] 2019-04-10 04:08
@loftsmen so close it

**Comment by loftsmen** [comment] 2019-04-10 10:17
Permissions please :)

**Closed** 2019-04-10 13:25 UTC
