### ISSUE TITLE
Windows GC Error [nobj != get_count(fp)]

### ISSUE THREAD

**Issue by gbluma** [felix-lang/felix#102] opened 2017-09-14 17:56 UTC
There appears to be a bug in the Windows port of Judy, although there is a complex interaction between Judy and Felix, so it could really be anything. This issue is hard to pin down but seems to recur periodically. 

```
Assertion failed: nobj == get_count(fp), file C:/projects/felix/src/packages/gc.fdoc, line 1201
Error running 'build\\release\\host\\bin\\bootflx.exe -Ibuild\\release\\share\\lib\\plugins --test=build\\release -c --test=build\\release -od build\\release\\host\\lib\\rtl
build\\release\\share\\lib\\plugins\\toolchain_clang_osx.flx' exited with 3
```

As per John "When producing a build, the bug repeats reliably until it goes away." One possible explanation for this is that the builds artifacts are staggered (part from build A, part from build B) and this mismatch or misalignment is causing the bug. 

More notes from John:
 - It’s a fault in the Judy tables concerning the length of a varray (ALL objects in Felix are varrays).
 - It only happens in the bootstrap build under Python.

Subtasks:
 - [ ] Identify whether this is a bug that can only be triggered by a misconfigured build or a true GC logic bug.
 - [ ] Very that the build doesn't leave behind artifacts (more as due diligence, but still helpful)
 - [ ] Add some more diagnostics to the GC logic to characterize a bug like this.

**Comment by skaller** [comment] 2017-09-14 18:47
I'd bet the problem is due to the port being either wrong or not complete.
However the code appears to work on OSX and Linux, its the same code.

The source of the problem was that the Judy devs broke ISO C in two places.
The first is the new aliasing rules. That may have been fixed, but Felix disables
gcc aggressive optimisation based on C aliasing rules building the code anyhow.
I doubt MSVC++ would every implement something that would break
hundreds of programs (which is exactly what gcc did).

The more likely problem was the assumption that a long integer was 64 bits on
a 64 bit system. On Windows long is 32 bits, irrespective of the size of a
machine address. The fix involved a lot of messing about using uintptr_t
instead of long, the most tricky such fixes involved changing `~1L` to `~(uintptr_t)(-1L)`.

Tricky because in some places a plain integer is OK, in others it is 
deliberately a smaller size. Judy is a digital trie, with a very complex
mapping between the keys and the tree structure in which it swaps between
one node size and another based on pre-calculated tables and also on the
population count of the nodes. Were it written in Haskell it might be
comprehensible, perhaps even in C++, but its archaic C code which uses 
macros to share the code between 32 and 64 bit versions, and between
Judy1Arrays (key sets) and JudyLArrays (key to key mappings). Add C's idiot
implicit conversions to the mix and the code is plain incomprehensible.
I relied on visual inspection and guesses to perform the porting, not any
understanding of how the code actually works.

One mistake, or missing one case, would break Judy.
Such an error would impact only a particular combination of the
actual binary code of the key together with the current state of the
tree, in other words, it would only be triggered in a small number
of cases (such as, for example, splitting a near full node into two nodes,
which then causes a different kind of parent node to also need splitting).

So in the same environment it breaks the same way at the same place
every time, but if the process is running with even a 1 bit change in the
address space (of Judy) the behaviour can be entirely different.
Even the length of a date string could do this.

**Comment by gbluma** [comment] 2017-09-14 18:52
New error message from the last build.
```
Insertion into j_nalloc (000000F434EEBE90) failed: address 000000F4351A32F0, [nobj=2 != get_count(fp)=1]
Assertion failed: nobj == n_objects, file C:/projects/felix/src/packages/gc.fdoc, line 1205
Error running 'build\\release\\host\\bin\\bootflx.exe -Ibuild\\release\\share\\lib\\plugins --test=build\\release -c --test=build\\release -od build\\release\\host\\lib\\rtl build\\release\\share\\lib\\plugins\\toolchain_clang_osx.flx' exited with 3
```

**Comment by skaller** [comment] 2017-09-14 19:00
Maybe the thing to do is, when the error is detected, run an integrity
test on j_nalloc table. What's happening is plain, an attempt to insert
and entry specifying a length of 2 for a varrray failed, so the get
following it is failing, which means the length is considered to be 1.

Judy arrays always start as NULL pointers. Access to j_nalloc only
occurs in a few places in the GC.  I think you can ignore collection phase,
the bug would be happening before the first collection. I guess.
Maybe not :) Set FLX_REPORT_COLLECTIONS=1 to see when they
happen.

One of the tricks you may see in the build script is that it sets the
minimum memory to huge amount, to stop Judy crashing the GC during
collection. It used to crash very quickly with default memory (used to
be 1Meg or even less). The larger amount is based on the idea the
whole build process can run without doing a collection.

The test cases can't, because they're run (as shell processes) by a
single processing running flx in batch mode. That used to crash
a lot too.

Some bugs in Felix GC were found, and some in the Felix library
as well, and in the really old days in the compiler. To this day,
the webserver crashes after running for a couple of days due
to a memory leak. The only reason its up now is Shayne reboots the
server every 20 minutes or something silly.

**Comment by skaller** [comment] 2017-09-15 04:59
This build has a trace of insertions into j_nalloc: It fails very very fast.

https://ci.appveyor.com/project/skaller/felix/build/1.0.1312

Unfortunately I forgot to add a dump of the key being inserted.

**Comment by skaller** [comment] 2017-09-15 05:02
Inserting into j_nalloc=0000004BE6C970B0
  new j_nalloc=0000004BE6A9A090
  slot for insert=0000004BE6CD68A8
Insertion into j_nalloc (0000004BE6A9A090) failed: address 0000004BE6D35630, [nobj=2 != get_count(fp)=1]


So notice, the root changed after the insertion. So this isolates which
piece of code it is a bit: something that recreates the root node.

**Comment by gbluma** [comment] 2017-09-15 05:03
Ahh. that's interesting. 

I have another one on the way that should provide the type and name (maybe).

**Comment by gbluma** [comment] 2017-09-15 05:08
Haha.. Oops. Syntax error. :)

**Comment by skaller** [comment] 2017-09-15 05:19
Its unlikely to have anything to do with the type. There's some code in JudyCommon/JudyIns that calculates the offset in a node of a thingo. Its called "offset" and its an "int". One place it says
```
offset = ~offset;
```
which looks suspicious to me. I think int is 16 bits on windows? The formula is equivalent to 
```
offset = -offset - 1;
```
assuming no sign extension.

**Comment by gbluma** [comment] 2017-09-15 05:25
Does this `[#a=0,#d=0]` mean it's failing on an allocation or a record?

```
Insertion into j_nalloc (00000067D162F790) failed: address 00000067D18F9600, [nobj=2 != get_count(fp)=1]
  p==NULL: true
[gc] Allocated 00000067D18F9600, shape=bootflx::_a14997t_111958[1][2][#a=0,#d=0]
Assertion failed: nobj == n_objects, file C:/projects/felix/src/packages/gc.fdoc, line 1219
```

**Comment by gbluma** [comment] 2017-09-15 05:25
Sorry, I should read the code. `a` is allocations `d` is deallocations.

**Comment by skaller** [comment] 2017-09-15 05:30
I don't think they're maintained: for debugging, expensive to maintain. Not sure :-)
The problem has to be somewhere in judy/src/JudyCommon/JudyIns.c ..

**Comment by gbluma** [comment] 2017-09-15 05:58
I added some print statements to `JudyLIns()` and it now captures some of the steps that occur before it dies.

```
Updating gc root because: valid empty array
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: leaf is at max size
Updating gc root because: valid empty array
Updating gc root because: valid empty array
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: growing to a larger leaf
Updating gc root because: leaf is at max size
Insertion into j_nalloc (00000096A398DE90) failed: address 00000096A3C1BD10, [nobj=2 != get_count(fp)=1]
  p==NULL: true
[gc] Allocated 00000096A3C1BD10, shape=bootflx::_a14997t_111958[1][2][#a=0,#d=0]
Assertion failed: nobj == n_objects, file C:/projects/felix/src/packages/gc.fdoc, line 1219
```

**Comment by skaller** [comment] 2017-09-15 08:16
Yep, bad idea to change any sizes of things, the whole thing is finely tuned to particular sizes.
You really narrowed it down with leaf at max size thing. That triggers JudyCascade.
I added some starting debugs to that.

The thing to look for is bitwise operations on signed integers and unsigned integers that don't have a fixed size (eg unsigned long or long or whatever instead of Word_t or whatever). Not all these will be wrong but really no one should ever do bitwise and, or, complement on signed values.

BTW: your diagnostic says "gc root" of course it isn't, its the root node of a Judy array. The actual GC roots are an STL map and the machine stack :)

**Comment by skaller** [comment] 2017-09-15 23:19
So one thing I did, with the offset diagnostics, was look at the trace from both Travis and Appveyor. Of course, the output was different because the keys were different (being memory addresses).
The offset twiddling looks correct code though. Its used in many places. Sizeof(int) shouldn't matter.

**Comment by skaller** [comment] 2018-09-07 03:48
I think this bug was a problem in fbuild building Judy for 32 bit instead of 64 bit. The bug appears resolved by forcing Windows build to 64 bit.

**Closed by skaller** 2018-09-07 03:48 UTC
Labels: bug
